version: '2'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    working_dir: /data
    command: redis-server /usr/local/etc/redis/redis.conf
